### ISSUE TITLE
[$20] Grammar in registration confirmation is bad.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#100]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Register a new user.
3. Observe registration pop up bottom left of the screen. 

## Actual Result(s)
*  Message says user with email $email register successful.
## Expected Result(s)
* Message reads user has registered successfully. 
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43678021-ff073d42-97d9-11e8-86fb-5be94c502dfb.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069548 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069548 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069548 has been updated - it has been assigned to ksmacleod99.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069548
