### ISSUE TITLE
[$20] We Go Social is weird grammar.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#101]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Scroll down to the bottom of the page.
3. Observe the bottom right of the screen at the social media section.

## Actual Result(s)
*  Site says We Go Social
## Expected Result(s)
* Reads something more grammatically correct in English.  Follow us on Social Media, for example.
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43678054-53f3be52-97da-11e8-883e-1ed59c9e50be.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069547 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069547 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
@ksmacleod99, please sign-up with Topcoder X tool

**Comment by dustinTopcoder** [comment]
@ksmacleod99, please sign-up with Topcoder X tool

**Comment by dustinTopcoder** [comment]
@ksmacleod99, please sign-up with Topcoder X tool

**Comment by dustinTopcoder** [comment]
@ksmacleod99, please sign-up with Topcoder X tool

**Comment by ksmacleod99** [comment]
Uhm, well. The errors work.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069547 has been updated - it has been assigned to ksmacleod99.

**Comment by dustinTopcoder** [comment]
@ksmacleod99, I think you'll need to remove the "Open for pickup" label when you take the ticket.

**Comment by dustinTopcoder** [comment]
@ksmacleod99, is this issue fixed?  If so, we'll need to close it.

**Comment by ksmacleod99** [comment]
It is.

**Comment by ksmacleod99** [comment]
Do we know if manually closing will issue payment? This is a really good
guniea pig moment

**Comment by dustinTopcoder** [comment]
Gonna try!   Closing now.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069547

**Comment by dustinTopcoder** [comment]
Looks it did pay!
