### ISSUE TITLE
[$20] Quick Link should read Quick Links

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#102]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1.	Open the URL https://frontend.app.cloud.gov/
2.	Scroll down to the bottom of the page.
3.	Observe the bottom right center of the screen at the Quick Link section.

## Actual Result(s)
* Site reads Quick Link 
## Expected Result(s)
* Site should say Quick Links 
## Frequency
* 5/5

## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43678095-e94aeebc-97da-11e8-89a6-6549ac8afbce.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069546 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069546 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069546 has been updated - it has been assigned to ksmacleod99.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069546
