### ISSUE TITLE
[$50] User is not notified when they are approved as NoK

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#104]
## Target URL 
https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login
3. Follow the steps to become NoK.
4. Wait for an Administrator to approve this.
5. Once verification from Admin that approval has occurred, check email. 

## Actual Result(s)
* No notificatoin that approval has been granted. 
## Expected Result(s)
* User is notified that they have been approved.
## Frequency
* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069544 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069544 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069544 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069544
