### ISSUE TITLE
[$20] Users cannot hit enter to login.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#105]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Fill in login information
3. Hit enter.

## Actual Result(s)
* Nothing happens.
## Expected Result(s)
*  User is able to login.
## Frequency
* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069541 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069541 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069541 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069541
