### ISSUE TITLE
[$50] Notifications show even when unsubscribe is checked. 

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#107]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Fill in login information
3. Login
4. Navigate to Dashboard.
5. Select Notification Preferences.
6. Set all Notification Preferences to unsubscribe all.

## Actual Result(s)
*  Notifications still show.

## Expected Result(s)
*  Notifications go away.

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/44170569-bf0abc80-a0a5-11e8-809c-52e2b094d730.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069542 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069542 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069542 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069542
