### ISSUE TITLE
[$50] When submitting a NoK request for a user that already has a NoK there is no notification to user.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#108]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a regular user
3. Select a user that already has a NoK.
4. Fill out the NoK request.

## Actual Result(s)
* User is not alerted that there is already a NoK.

## Expected Result(s)
*  User would be alerted a NoK already exsists.

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069619 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069619 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069619 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069619
