### ISSUE TITLE
[$30] When data doesn't exist users are given ugly timed error messages. 

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#111]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Fill in login information
3. Hit enter.
4. Search for anyone.
5. Select a record.
6. Observe errors.

## Actual Result(s)
* Users are shown ugly timed messages when the data does not exist.

## Expected Result(s)
*  Data actually exists or the record is not displayed.

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/44171524-67ba1b80-a0a8-11e8-8583-38899c866d0f.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069615 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069615 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069615 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069615
