### ISSUE TITLE
[$200] Administrators cannot create / grant  administrator access to others.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#112]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login with an Administrator account.
3. Navigate to dashboard.

## Actual Result(s)
*  Admin user has no ability to create or grant administrator access to other users.

## Expected Result(s)
*  Admin users can allow other admins.

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069614 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069614 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069614 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Closed:  Dupe #116
