### ISSUE TITLE
[$50] Administrators do not have the ability to edit their own profile

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#114]
## Target URL 

https://frontend.app.cloud.gov/admin/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as an administrator.
3. Navigate to the dashboard.

## Actual Result(s)
*  Only administrator functions are available.

## Expected Result(s)
*  All functions are available, for example user has the ability to edit their name or notification settings. 

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/44171964-b6b48080-a0a9-11e8-9480-2540488e4884.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069562 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069562 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069562 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069562
