### ISSUE TITLE
[$50] Flagged posts do not actually show up in the administrator dashboard

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#115]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a regular user.
3. Flag a post.
4. Login as an administrator.
5. Navigate to the Flagged posts section.

## Actual Result(s)
*  Flagged posts do not appear.

## Expected Result(s)
*  Flagged posts actually appear. 

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/44172034-f2e7e100-a0a9-11e8-8a7e-1bdac20f56ff.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069561 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069561 has been updated - the new changes has been updated for this ticket.

**Comment by jiangliwu** [comment]
the reason is frontend delete post, but didn't delete flag, that caused endpoint /api/v1/flags return 400 error, so test this issue need remove all rows from database table **_Flags_** first, then try to create add flag in frontend.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069561 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069561
