### ISSUE TITLE
[$400] Administrator cannot delete/manage user accounts. 

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#116]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as administrator
3. Navigate to Users.

## Actual Result(s)
* No option do anything with user accounts.

## Expected Result(s)
*  Administrator has the ability to delete or manage user accounts as necessary. 

## Frequency
* 5/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/44172149-4823f280-a0aa-11e8-8b93-ad92e72b6617.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069560 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069560 has been updated - the new changes has been updated for this ticket.

**Comment by jiangliwu** [comment]
@dustinTopcoder in fact, admin can deActive/edit/create user, but it should not delete user, can you confirm this?

**Comment by dustinTopcoder** [comment]
That's correct.  We should just deactivate the user.  As such, the admin should be able to reactivate a user as well.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069560 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069560 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069560 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069560
