### ISSUE TITLE
[$30] Add loading page to search feature

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/va-online-memorial-frontend#124]
## Target URL
https://frontend.app.cloud.gov/search

## Steps to Reproduce
Open the URL https://frontend.app.cloud.gov/
Search for any individual using top search bar or search filters
Click 'Update Results'

### Actual Result(s)
Page does not indicate click event triggered anything until query results load.

### Expected Result(s)
A loading overlay with a spinner or other indicator that results are loading until results are populated.

### Frequency
5/5

### Environment Details
Device(s): Laptop
Operating System: iOS 10.13.5
Browser(s): Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30070580 has been created for this ticket.

**Comment by ksmacleod99** [comment]
related to #51

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30070580 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30070580
