### ISSUE TITLE
Filtering is not working other than the 'Burial Location' and 'Branch of service'

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#13]
## Target URL

https://frontend.app.cloud.gov/

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User
3. Click Search button
4. Enter 'Branch of service' as US ARMY
5. Click 'Update Results' button
6. Check the 'Charles Greer' Mar 18, 1931 - Dec 3, 2012  - https://frontend.app.cloud.gov/dashboard/4
7. Enter DOB as Mar 18, 1931
8. Click 'Update Results' button
9. Now go to page no 3
10. Check the DOB of Ronald Dale Baker > Mar 14, 1931 - https://frontend.app.cloud.gov/dashboard/293956

## Actual Result(s)

- Filtering is not working other than the 'Burial Location' and 'Branch of service'

## Expected Result(s)

- Must able to filter from other options as well

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![8](https://user-images.githubusercontent.com/4592712/41741128-d341b3a0-755f-11e8-9956-bd048ba1aa26.jpg)

**Comment by ramillim** [comment]
Another bug I'm seeing is that when you enter 3 18 1931 and click Update Results, it becomes 3 17 1931

**Comment by ramillim** [comment]
Oh wow, what a heinous bug. The numerical date part was created by parsing .getDay() from the Date class. .getDay() is the numerical day of the week from 0 - 6 (Monday - Sunday). This should be .getDate(), which gets you 1-31. I will check if this resolves the filtering issue or if there are other items after I make this fix.

Unit tests would've probably caught that, but alas, this project has no unit tests :)
