### ISSUE TITLE
Can enter empty 'Story'

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#21]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Write Story'
8. Enter spaces for 'Title' field; and 'Message' field
9. Click 'Post Story' and Observe

## Actual Result(s)

- Can enter empty 'Story'

## Expected Result(s)

- Must validate the two field when user is going to post a 'Story'

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/JlRCsKJak5X

**Comment by ramillim** [comment]
This issue looks like it's already fixed.  "Title should not be empty" appears on the bottom left.

**Comment by ksmacleod99** [comment]
I can also post with spaces on this one
