### ISSUE TITLE
Can enter empty 'Testimonial'

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#23]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Testimonial'
8. Enter spaces for 'Title' field; and 'Testimonial' field
9. Click 'Post Testimonial' and Observe

## Actual Result(s)

- Can enter empty 'Testimonial'

## Expected Result(s)

- Must validate the two field when user is going to post a 'Testimonial'

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/EVO19TiM2

**Comment by ramillim** [comment]
This one is already fixed, just like the Story form in #21 
It was fixed on the server-side, so maybe this video was recorded when the frontend was pointing to an older version of the rest-api.

**Comment by ksmacleod99** [comment]
I was able to post with spaces
