### ISSUE TITLE
'Salute' button icon is too close to the text

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#25]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Stories' section and click on 'Read more' from one of the stories
8. Check the 'Salute' button 

## Actual Result(s)

- 'Salute' button icon is too close to the text

## Expected Result(s)

- Must have some space

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![20](https://user-images.githubusercontent.com/4592712/41749919-cfc034d0-757e-11e8-95ec-8998ea01c261.jpg)

**Comment by ramillim** [comment]
@nagano564

**Comment by ramillim** [comment]
@dustinWeaver This was fixed in https://github.com/topcoderinc/va-online-memorial-frontend/pull/69
it just wasn't referenced from that PR

**Comment by ksmacleod99** [comment]
fixed in PR #69 and paid
