### ISSUE TITLE
Post view count is not updating

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#28]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Stories' section and click on 'Read more' from one of the stories
8. Check the 'Reads' count > 1333
9. Close the post and open it again
10. Check the 'Reads' count > 1333

## Actual Result(s)

- Post view count is not updating

## Expected Result(s)

- Must increase the count of the post view count when user opens an article

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![23](https://user-images.githubusercontent.com/4592712/41750183-1ec6ff9a-7580-11e8-9f76-2761af812c71.jpg)

**Comment by ramillim** [comment]
Reads, Salutes, and Shares are all hard coded to be the numbers displayed above.
Of the three, only Salutes are currently implemented.

There's a comment in the API code about how statistics are currently out of scope.
https://github.com/topcoderinc/va-online-memorial-rest-api/blob/master/modules/stories/services/StoryService.js#L266-L270

**Comment by ramillim** [comment]
@dustinWeaver This one should have a phase2 label.
