### ISSUE TITLE
'Salute' state is not displayed correctly

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#31]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Upload' button and upload 2 images with a Caption
8. Click on 'Photos' section
9. Click on the 2nd image and mark it as 'Saluted'
10. Now close the popup
11. Click on the first image
12. Click on the '>' icon or 'Next Photo'
13. Observe the 'Salute' button; displayed as 'Salute' NOT 'Saluted'

## Actual Result(s)

- 'Salute' state is not displayed correctly when user navigate through the next button

## Expected Result(s)

- Must display the 'Salute' state correctly

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/9CUwKicw9F

**Comment by ramillim** [comment]
This appears to already be fixed.

**Comment by ramillim** [comment]
@dustinWeaver This one needs the retest label since I couldn't repro it.

**Comment by dustinWeaver** [comment]
@ksmacleod99, can you retest then when you get a chance?  If it's working, we can close it.

**Comment by ksmacleod99** [comment]
@dustinWeaver it is fixed, but there needs to be just a little style tweaking post state change. Would you like me to keep this issue open, or create a new one for this?
![2018-07-08-10-46-frontend app cloud gov](https://user-images.githubusercontent.com/28678836/42420996-455c0a28-829c-11e8-83a8-2521074ce6cb.png)

**Comment by dustinWeaver** [comment]
@ksmacleod99, let's open a new issue for the styling and just reference this issue.
