### ISSUE TITLE
'Find a Veteran', 'Show what's New' and 'Become a member' buttons are not working

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#42]
## Target URL

https://frontend.app.cloud.gov/

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click on the 'Find a Veteran', 'Show what's New' and 'Become a member' buttons

## Actual Result(s)

- 'Find a Veteran', 'Show what's New' and 'Become a member' buttons are not working

## Expected Result(s)

- Button must function properly
- 'Find a Veteran': Must trigger the search
- 'Become a member': Must trigger the registration

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![31 1](https://user-images.githubusercontent.com/4592712/41794141-002ad166-7624-11e8-9c01-28b39a1500d6.jpg)
![31 2](https://user-images.githubusercontent.com/4592712/41794143-003f83ea-7624-11e8-8c95-2becf952a934.jpg)

**Comment by dustinWeaver** [comment]
Let's do this for these:

Find a Veteran:  Take you to the search screen
Become a Member: Take you to the signup screen

Let's leave "Show What's New" for now.

**Comment by ramillim** [comment]
@dustinWeaver if you could chime in on this design question:

There's a container called "Register" that could be serving as the Become a Member signup page, but it has no design and looks like this. It's also broken:
![image](https://user-images.githubusercontent.com/3946035/41813541-fd081060-7705-11e8-98be-56af798f3230.png)

I recommend using the form that appears when you click on Register in the top right.  It's not broken out into its own component, just part of the MainHeader component. I could extract it into its own and put it into its own page (which would require a design spec), or probably the quickest fix is clicking on become a member makes this popup box appear.

![image](https://user-images.githubusercontent.com/3946035/41813565-5bfa1ffa-7706-11e8-9ba0-3881f05feec7.png)

**Comment by ramillim** [comment]
I'm going to go with the quickfix method and open a PR and just let me know if you want to implement a separate route for /register
