### ISSUE TITLE
[$50] The proof Download button is not working

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#44]
## Target URL

https://frontend.app.cloud.gov/admin/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Send NOK Request' button
8. Enter all the required details and submit
9. Click on Username and go to profile page
10. Click NOK Request > For Review
11. Click Download

## Actual Result(s)

- The proof Download button is not working

## Expected Result(s)

- Must download the file

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![33](https://user-images.githubusercontent.com/4592712/41804192-b3e63096-7657-11e8-9e6f-f24a01e40af6.jpg)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069641 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069641 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069641 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069641
