### ISSUE TITLE
[$30] Clicking on 'Veteran's Profile' button will redirect the page to a wrong one

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#45]
## Target URL

https://frontend.app.cloud.gov/admin/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Send NOK Request' button
8. Enter all the required details and submit
9. Click on Username and go to profile page
10. Click NOK Request > For Review
11. Click 'Veteran's Profile' button

## Actual Result(s)

- Clicking on 'Veteran's Profile' button will redirect the page to a wrong one

## Expected Result(s)

- Must redirect the page to 'Robert Ray Hutchins' profile

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/kTA9Bg4M

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069640 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069640 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069640 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069640
