### ISSUE TITLE
Search by veteran name is not working 

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#50]
## Target URL

https://frontend.app.cloud.gov/search

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Enter 'Charlie Bruce Johnson' and click Search button
4. Observe

## Actual Result(s)

- Search by veteran name is not working 

## Expected Result(s)

- Must popup the veteran name in the search result list

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/lJJEL0mvPWp

**Comment by dustinTopcoder** [comment]
Dupe or related to #117
