### ISSUE TITLE
[$30] No message displayed when there is no result found

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#51]
## Target URL

https://frontend.app.cloud.gov/search

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Enter 'Branch of service' > Artillery and 'Burial Location' > Green Mount Cemetery and click Search button
4. Observe
5. Enter 'Branch of service' > Artillery and click Search button
6. Observe

## Actual Result(s)

- No message displayed when there is no result found
- If user didn't search via veteran's name result text always displayed as "125543 Results for “”"

## Expected Result(s)

- Must display message for empty result set "No Result(s) found"
- Must remove the ' for “”' and only display "125543 Results"; If user search via veteran then system can display "100 Results for “Charlie Bruce Johnson”"

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![39 1](https://user-images.githubusercontent.com/4592712/41810604-e4c7c00c-76c6-11e8-9f0d-b9e870786d63.jpg)
![39 2](https://user-images.githubusercontent.com/4592712/41810606-e4da961e-76c6-11e8-9e59-d9dd1e1814e5.jpg)
![39 3](https://user-images.githubusercontent.com/4592712/41810614-2100ee9a-76c7-11e8-950f-01c9f8c5a593.jpg)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069623 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069623 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069623 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069623
