### ISSUE TITLE
'Username' is displayed on the login screen but doesn't supports for login

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#6]
## Target URL

https://frontend.app.cloud.gov/

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Click Login
3. Enter valid Username and Password
4. Click Login Account

## Actual Result(s)

- 'Username' is displayed on the login screen but doesn't supports for login

## Expected Result(s)

- Must remove 'Username' from the login screen or Must support username for login

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![1](https://user-images.githubusercontent.com/4592712/41740522-ea57568c-755d-11e8-85d4-8a0b9df31eb5.jpg)

**Comment by ramillim** [comment]
Just doing a preliminary investigation. This issue also requires updates to the backend. It appears that only email login was implemented there.
https://github.com/topcoderinc/va-online-memorial-rest-api/blob/master/modules/security/services/SecurityService.js#L76

**Comment by ramillim** [comment]
@dustinWeaver I had to fix this on the backend https://github.com/topcoderinc/va-online-memorial-rest-api/pull/4
