### ISSUE TITLE
[$50] 'Veteran Name' and 'Submit Proof' fields won't reset when user click on 'Send Request' button

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#63]
## Target URL

https://frontend.app.cloud.gov/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click on username
4. Click 'NOK Request'
5. Select 'Veteran Name' and upload a file
6. Click 'Send Request' button
7. Click 'Send Request' button again

## Actual Result(s)

- 'Veteran Name' and 'Submit Proof' fields won't reset when user click on 'Send Request' button

## Expected Result(s)

- Must reset the field so that user can't accidentally add another record

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/UWeeKgGQlq

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069636 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069636 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069636 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069636
