### ISSUE TITLE
[$50] Can't download the Submitted Proof

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#65]
## Target URL

https://frontend.app.cloud.gov/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click on username
4. Click 'NOK Request'
5. Select 'Veteran Name' and upload a file
6. Click 'Send Request' button
7. Now scroll down and click on 'View Submitted Proof' button
8. Click Download

## Actual Result(s)

- Can't download the Submitted Proof

## Expected Result(s)

- User must able to download the 'Submitted Proof'

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![47](https://user-images.githubusercontent.com/4592712/41815492-5b5eccf4-7732-11e8-9cc3-d64313c2335f.jpg)

**Comment by ksmacleod99** [comment]
I am getting an unsuccessful HTTP response for this one and #44

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069557 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069557 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069557 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069557
