### ISSUE TITLE
'Notification Preferences' are not working

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#66]
## Target URL

https://frontend.app.cloud.gov/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click on username
4. Click 'Notification Preferences'
5. Enable site notifications and email notifications
6. Click 'Save Changes' button
7. Post a story and observe

## Actual Result(s)

- 'Notification Preferences' are not working

## Expected Result(s)

- 'Notification Preferences' must trigger the site notifications and email notifications

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/2ikpI75Jvg

**Comment by dustinTopcoder** [comment]
Dupe of #107
