### ISSUE TITLE
'Deactivate Accounts' button displays a message but function isn't working

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#67]
## Target URL

https://frontend.app.cloud.gov/setting

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click on username
4. Click 'Basic Details'
5. Click 'Deactivate Accounts' button

## Actual Result(s)

- 'Deactivate Accounts' button displays a message but function isn't working

## Expected Result(s)

- Must deactivate the account

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![49](https://user-images.githubusercontent.com/4592712/41816224-0c7d0412-7745-11e8-953b-42d500405c7a.jpg)

**Comment by ramillim** [comment]
@dustinWeaver just a heads up that the fix for this also required a PR to va-online-memorial-rest-api
