### ISSUE TITLE
'Reset' filter button is not working

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#8]
## Target URL

https://frontend.app.cloud.gov/search

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User
3. Click Search
4. Select 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click Reset filter

## Actual Result(s)

- 'Reset' filter button is not working

## Expected Result(s)

- Must reset all the filtered data when user click on the reset button

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![3](https://user-images.githubusercontent.com/4592712/41741025-88739a5a-755f-11e8-8412-2eb319135e1c.jpg)

**Comment by ramillim** [comment]
Unable to reproduce this issue. Clicking on Reset Filter resets all fields on the form.

**Comment by dustinWeaver** [comment]
This works for me as well on OS X Chrome.  Let's close for now.
