### ISSUE TITLE
Login behavior for search and profile views

### ISSUE THREAD

**Issue by dustinWeaver** [topcoderinc/va-online-memorial-frontend#86]
As an anonymous user, I should be able to:

- Search and find profiles
- View stories, badges, etc on a profile

To write or edit anything, I would need to be logged in.

**Comment by dustinWeaver** [comment]
@ksmacleod99, this one came from a request from the client.  Perhaps we could task this out to someone?

**Comment by dustinTopcoder** [comment]
@ksmacleod99, any update on this?

**Comment by ksmacleod99** [comment]
totally lost track of this; I just pinged Ramil to see if he will have time.
