### ISSUE TITLE
[$150] User not able to verify email address after sign up.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#91]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Click the register button
3. Create account
4. Observe banner at the bottom of the box informing the user the will need to verify the email address. 
5. Click Register Account button
6. Check email associated with the account, no email
7. Login using username/password
## Actual Result(s)

* User is allowed to login, however, no email is ever received.
## Expected Result(s)

* User must verify email address before being allowed to proceed.
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![image](https://user-images.githubusercontent.com/19790104/43369434-500766e2-933c-11e8-8522-7b30e9ecf753.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069556 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069556 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069556 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069556 has been updated - it has been assigned to jiangliwu.

**Comment by jiangliwu** [comment]
update backend -> config.default.json -> email section, then try to register again.

**Comment by ksmacleod99** [comment]
Fixed in the rest-API repo

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069556
