### ISSUE TITLE
[$30] User Login name is case sensitive.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#92]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Hit the login button.
3. Type in username in a different case than you created it in.
4. Observe Login Failure.

## Actual Result(s)

* User names are case sensitive.
## Expected Result(s)

*  User names are NOT case sensitive.
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log

![image](https://user-images.githubusercontent.com/19790104/43369513-e21ab90c-933d-11e8-9024-60f6c3dfb75d.png)

![image](https://user-images.githubusercontent.com/19790104/43369515-ec25fb82-933d-11e8-9fd1-fd7af3a5d548.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069555 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069555 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069555 has been updated - it has been assigned to jiangliwu.

**Comment by ksmacleod99** [comment]
Hey @jiangliwu, I'm still getting credential errors when I test this. I should be able to log in with my user name in all caps, correct?

**Comment by jiangliwu** [comment]
Do you also merge backend PR?

**Comment by ksmacleod99** [comment]
yes I did :)

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069555
