### ISSUE TITLE
[$50] Submitting Proof for NoK does not appear to attach anything.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#93]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login
3. Click on user name to navigate to profile.
4. Click NoK Request
5. Select Veteran Name
6. Click the Browse button to submit proof.
7. Select proof file.
8. Select Open
9. Observe Submit Proof Box.

## Actual Result(s)
* Submit proof box still appears to be empty. 
## Expected Result(s)
* Submit proof box shows user there is a file that is about to be submitted.
## Frequency
* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43369558-b1ec6608-933e-11e8-843f-ce93f87b1cd5.png)
![image](https://user-images.githubusercontent.com/19790104/43369560-bae78738-933e-11e8-8010-3d774980ddfc.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069554 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069554 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069554 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069554
