### ISSUE TITLE
[$350] Clicking on a notification does not take you to the event. 

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#94]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login.
3. Click on the notification icon.
4. Click on a notification.
5. Observe.

## Actual Result(s)
*  Nothing Happens
## Expected Result(s)
* User is taken to the notification 
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
http://www.screencast.com/t/KHkwWETf

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069553 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069553 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069553 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069553 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069553
