### ISSUE TITLE
[$50] Notifications don't clear when click or on login/logout.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#95]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login
3. Observe notifications
4. Click on a notification OR Log out
5. Observe notifications again 

## Actual Result(s)
* Notifications stay. 
## Expected Result(s)
* Notifications go away after user has looked at them. 
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43369789-d66f8b4c-9341-11e8-965f-375de8e12c38.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069552 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069552 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069552 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069552
