### ISSUE TITLE
[$50] Save changes on profile doesn't work

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#96]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login
3. Navigate to basic details in profile.
4. Update something.
5. Navigate away from basic details page.
6. Return to basic details page.
7. Observe value previously changed.

## Actual Result(s)
* The value changed remains unchanged. 
## Expected Result(s)
* The value changed actually changes. 
## Frequency

* 5/5
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
http://www.screencast.com/t/UbiCflYvhdf

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069551 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069551 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069551 has been updated - it has been assigned to jiangliwu.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069551
