### ISSUE TITLE
[$50] ProfileCard Component needs refinement

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/va-online-memorial-frontend#97]
the ProfileCard component is using the default.json data completely, so even if the profile has a profile photo, it doesn't get displayed because the placeholder is displayed

**Comment by dustinTopcoder** [comment]
Dupe of #96

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069550 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069550 has been updated - the new changes has been updated for this ticket.
