### ISSUE TITLE
[$20] Grammar in Error Message is terrible.

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#98]
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Attempt to Login when the site is unreachable.
3. Observe error message.

## Actual Result(s)
* Message says Network can not reachable, please check. 
## Expected Result(s)
* Message should read Network cannot be reached. 
## Frequency
* 5/5 (When login is not possible)
## Environment Details

* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)
## Image(s)/Video(s)/Console Log/Crash Log
![image](https://user-images.githubusercontent.com/19790104/43677949-a0aba20c-97d8-11e8-9bc1-718ecc60d97c.png)

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069549 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069549 has been updated - the new changes has been updated for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069549 has been updated - it has been assigned to BrandonT.

**Comment by dustinTopcoder** [comment]
Payment failed: [500]: Failed to get topcoder member id.

**Comment by dustinTopcoder** [comment]
Payment failed: [500]: Failed to get topcoder member id.

**Comment by brandontiqui** [comment]
I just registered for the challenge - maybe my member id is linked now.  Before the register button was disabled.

**Comment by dustinTopcoder** [comment]
Payment failed: [500]: Failed to get billing detail for the project.

**Comment by dustinTopcoder** [comment]
@ksmacleod99, Direct is having some issues right now, so that's why this isn't going through.  We can try again in an hour by doing the following: 
1. Add "Fix accepted" label
1. Close the issue manually

**Comment by dustinTopcoder** [comment]
Let's try this again.

**Comment by dustinTopcoder** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069549
